### ISSUE TITLE
지뢰 생성 시 중복 확인

### ISSUE THREAD

**Issue by egwkim** [RODELA5/jamsin-web-game#1]
지뢰 생성 과정에서 중복된 위치에 지뢰가 생성되는 경우가 발생

<img width="350" src="https://user-images.githubusercontent.com/35051914/184600921-6628d979-cc69-458e-9c0d-7ba9b2eb9411.png"></img>

크기 5, 지뢰 개수 25로 한 결과
-1이 아닌 칸 존재

해결방법
1. for 문 안에 while문 추가하여 지뢰가 없는 곳 나올 때까지 반복
2. itertools.product, random.sample 사용하여 unique한 x, y 좌표 고르기

등등...

**Comment by HURDOO** [comment]
![image](https://user-images.githubusercontent.com/64835865/184615568-49a3890a-81b4-45e2-9774-aab38c1c105c.png)

**Comment by egwkim** [comment]
👍👍
