### ISSUE TITLE
게임 종료 메시지 표시 (오목, 지뢰찾기)

### ISSUE THREAD

**Issue by egwkim** [RODELA5/jamsin-web-game#7]
게임 종료 메시지 표시
오목은 승/패 여부
지뢰찾기는 실제 지뢰 위치 표시(틀렸을 때), 걸린 시간 표시

**Comment by egwkim** [comment]
\+ 지뢰찾기에서 점수 (연 칸 개수) 보여주기

**Comment by HURDOO** [comment]
minesweeper 지뢰 위치 완료 d78cfc7

**Comment by egwkim** [comment]
오목 종료 메시지 완료 15d04a7
